site_name: OSH è·æ¥­å®‰å…¨è¡›ç”Ÿ
site_description: è·æ¥­å®‰å…¨è¡›ç”Ÿæ–‡ä»¶é›†
site_url: https://yuch-hank.github.io/OSH/
site_dir: site
docs_dir: docs

theme:
  name: material
  logo: src/image.png
  favicon: src/image.png
  language: zh-TW
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.path
    - toc.follow
    - toc.integrate
    - content.footnote.tooltips
  icon:
    annotation: material/plus-circle

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - sane_lists
  - admonition
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: "1-3"
  - pymdownx.arithmatex:
      generic: true
      inline_syntax: ["$", "$$"]
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
  - src/js/math-render.js
  - https://cdn.jsdelivr.net/npm/mermaid@10.9.1/dist/mermaid.min.js
  - src/js/mermaid-init.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - src/js/tablesort.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css
  - src/css/style.css

nav:
  - ğŸ  é¦–é : index.md
  - ğŸ“ TODO: ToDo.md

  - ğŸ… æ³•è¦ä¾æ“š:
      - è·æ¥­å®‰å…¨è¡›ç”Ÿæ³•: A_æ³•è¦ä¾æ“š/è·å®‰æ³•.md
      - æ³•è¦åƒè€ƒé€£çµ: A_æ³•è¦ä¾æ“š/æ³•è¦åƒè€ƒé€£çµ.md
      - CNS èˆ‡æŒ‡å¼•: A_æ³•è¦ä¾æ“š/CNS_èˆ‡æŒ‡å¼•.md

  - ğŸ…‘ ç®¡ç†åˆ¶åº¦:
      - å®‰å…¨è¡›ç”Ÿçµ„ç¹”: B_ç®¡ç†åˆ¶åº¦/å®‰å…¨è¡›ç”Ÿçµ„ç¹”.md
      - å®‰å…¨è¡›ç”Ÿç®¡ç†å“¡: B_ç®¡ç†åˆ¶åº¦/å®‰å…¨è¡›ç”Ÿç®¡ç†å“¡.md
      - å®‰å…¨è¡›ç”Ÿè¨ˆç•«: B_ç®¡ç†åˆ¶åº¦/è¨ˆåŠƒæ›¸.md
      - åˆ†ç´šç®¡ç†: B_ç®¡ç†åˆ¶åº¦/åˆ†ç´šç®¡ç†.md
      - è·ç½è£œå„Ÿ: B_ç®¡ç†åˆ¶åº¦/è·ç½è£œå„Ÿ.md
      - äº‹æ•…é€šå ±èˆ‡å‚™æŸ¥: B_ç®¡ç†åˆ¶åº¦/é€šå ±èˆ‡å‚™æŸ¥.md

  - ğŸ…’ å±å®³:
      - å±å®³ç¸½è¦½: C_å±å®³/å±å®³ç¸½è¦½.md
      - åŒ–å­¸æ€§å±å®³: C_å±å®³/åŒ–å­¸æ€§å±å®³.md
      - ç‰©ç†æ€§å±å®³: C_å±å®³/ç‰©ç†æ€§å±å®³.md

  - ğŸ…“ ä½œæ¥­èˆ‡å ´æ‰€:
      - ä½œæ¥­: D_ä½œæ¥­èˆ‡å ´æ‰€/ä½œæ¥­ç¸½è¦½.md
      - å ´æ‰€: D_ä½œæ¥­èˆ‡å ´æ‰€/å ´æ‰€.md
      - å±€é™ç©ºé–“ä½œæ¥­: D_ä½œæ¥­èˆ‡å ´æ‰€/å±€é™ç©ºé–“ä½œæ¥­.md
      - å™ªéŸ³ä½œæ¥­å ´æ‰€: D_ä½œæ¥­èˆ‡å ´æ‰€/å™ªéŸ³ä½œæ¥­å ´æ‰€.md

  - ğŸ…” è¨­å‚™èˆ‡é˜²è­·:
      - æ©Ÿæ¢°è¨­å‚™: E_è¨­å‚™èˆ‡é˜²è­·/æ©Ÿæ¢°è¨­å‚™.md
      - ç‡Ÿé€ è¨­æ–½: E_è¨­å‚™èˆ‡é˜²è­·/ç‡Ÿé€ è¨­æ–½.md
      - å€‹äººé˜²è­·å…·: E_è¨­å‚™èˆ‡é˜²è­·/å€‹äººé˜²è­·å…·.md
